#!/bin/sh
NAME="${1:-resume}"
CONFIG="${2:-default}.config.json"

md-to-pdf --config-file $CONFIG $NAME.md
cp "$NAME.pdf" "docs/lekhacduyanh_$NAME.pdf"
rm $NAME.pdf

open "docs/lekhacduyanh_$NAME.pdf"
